# Generated by Django 6.0.3 on 2026-03-17 23:23

import django.db.models.deletion
from django.db import migrations, models

def create_default_category(apps, schema_editor):
    Category = apps.get_model('BookListAPI', 'Category')
    Category.objects.create(id=1, title='Default', slug='default')

def reverse_create_default_category(apps, schema_editor):
    Category = apps.get_model('BookListAPI', 'Category')
    Category.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('BookListAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(create_default_category),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='BookListAPI.category'),
        ),
    ]
